ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS builder
ARG APPLICATION_JAR=target/openworkflow-studio-spring-1.0.0-SNAPSHOT.jar
WORKDIR /builder
COPY ${APPLICATION_JAR} application.jar
RUN java -Djarmode=tools -jar application.jar extract --layers --destination extracted

FROM ${BASE_IMAGE}
ARG APP_UID=10001
ARG APP_GID=10001
WORKDIR /application
COPY --from=builder --chown=${APP_UID}:${APP_GID} /builder/extracted/dependencies/ ./
COPY --from=builder --chown=${APP_UID}:${APP_GID} /builder/extracted/spring-boot-loader/ ./
COPY --from=builder --chown=${APP_UID}:${APP_GID} /builder/extracted/snapshot-dependencies/ ./
COPY --from=builder --chown=${APP_UID}:${APP_GID} /builder/extracted/application/ ./
EXPOSE 8080
USER ${APP_UID}:${APP_GID}
ENTRYPOINT ["java", "-jar", "application.jar"]
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
