# Licensed to the Apache Software Foundation (ASF) under one or more contributor license
# agreements. See the NOTICE file distributed with this work for additional information regarding
# copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0.
framework: quarkus
replicas: 1
image:
  repository: forwardmeasure/openworkflow-studio-quarkus
  tag: 1.0.0-SNAPSHOT
  digest: ""
  pullPolicy: IfNotPresent
apiUpstream: http://openworkflow-definition-quarkus:8080
environmentName: Acceptance
ingress:
  enabled: false
  className: nginx
  host: openworkflow.local
serviceAccount:
  create: true
  name: ""
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile: {type: RuntimeDefault}
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities: {drop: [ALL]}
resources:
  requests: {cpu: 50m, memory: 192Mi}
  limits: {cpu: "1", memory: 512Mi}
terminationGracePeriodSeconds: 30
disruptionBudget:
  enabled: true
  minAvailable: 1
networkPolicy:
  enabled: false
  extraEgress: []
telemetry:
  serviceName: ""
  otlpEndpoint: ""
  resourceAttributes: "service.namespace=forwardmeasure-openworkflow"
  injectJava: false
  protocol: grpc
  propagators: tracecontext,baggage
  tracesExporter: otlp
  metricsExporter: otlp
  logsExporter: otlp
