#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels: {app: postgresql}
  template:
    metadata:
      labels: {app: postgresql}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.images.postgresql.repository }}{{ if .Values.images.postgresql.digest }}@{{ .Values.images.postgresql.digest }}{{ else }}:{{ .Values.images.postgresql.tag }}{{ end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - {name: POSTGRES_DB, value: {{ .Values.database.name | quote }}}
            - {name: POSTGRES_USER, value: {{ .Values.database.username | quote }}}
            - {name: POSTGRES_PASSWORD, value: {{ .Values.database.password | quote }}}
          ports:
            - {name: postgresql, containerPort: 5432}
          readinessProbe:
            exec: {command: ["pg_isready", "-U", {{ .Values.database.username | quote }}]}
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector: {app: postgresql}
  ports:
    - {name: postgresql, port: 5432, targetPort: postgresql}
{{- end }}
