# Licensed to the Apache Software Foundation (ASF) under one or more contributor license
# agreements. See the NOTICE file distributed with this work for additional information regarding
# copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the License. You may obtain a
# copy of the License at https://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable
# law or agreed to in writing, software distributed under the License is distributed on an "AS IS"
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License
# for the specific language governing permissions and limitations under the License.
quarkus:
  application:
    name: openworkflow-definition-management-quarkus
  arc:
    exclude-types: com.forwardmeasure.jpa.quarkus.QuarkusTenantResolver
  http:
    host: 0.0.0.0
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${OPENWORKFLOW_DATABASE_URL:jdbc:postgresql://localhost:5432/openworkflow}
    username: ${OPENWORKFLOW_DATABASE_USERNAME:openworkflow}
    password: ${OPENWORKFLOW_DATABASE_PASSWORD:openworkflow}
  oidc:
    auth-server-url: ${OPENWORKFLOW_KEYCLOAK_ISSUER:http://localhost:8080/realms/openworkflow}
    application-type: service
  hibernate-orm:
    multitenant: SCHEMA
    packages: com.forwardmeasure.jpa.identity.entity,com.forwardmeasure.openworkflow.definition.domain.entity
    schema-management:
      strategy: none
openworkflow:
  authorization:
    issuer: ${OPENWORKFLOW_KEYCLOAK_ISSUER:http://localhost:8080/realms/openworkflow}
    client-id: forwardmeasure-openworkflow
    client-secret: ${OPENWORKFLOW_CLIENT_SECRET}
    request-timeout: 5S
    decision-ttl: 5S
    maximum-cache-entries: 10000
    policy-version: v1
