<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more contributor license
  agreements. See the NOTICE file distributed with this work for additional information regarding
  copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with the License. You may obtain
  a copy of the License at https://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable
  law or agreed to in writing, software distributed under the License is distributed on an "AS IS"
  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License
  for the specific language governing permissions and limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.forwardmeasure.openworkflow</groupId>
    <artifactId>forwardmeasure-openworkflow-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>
  <artifactId>openworkflow-execution-management-micronaut-binding</artifactId>
  <name>ForwardMeasure OpenWorkflow :: Execution Management :: Micronaut Binding</name>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.forwardmeasure.platform</groupId>
        <artifactId>forwardmeasure-platform-micronaut-bom</artifactId>
        <version>${forwardmeasure.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.forwardmeasure.openworkflow</groupId>
      <artifactId>openworkflow-execution-jaxrs</artifactId>
    </dependency>
    <dependency>
      <groupId>com.forwardmeasure.openworkflow</groupId>
      <artifactId>openworkflow-execution-management-jpa</artifactId>
    </dependency>
    <dependency><groupId>com.forwardmeasure.openworkflow</groupId><artifactId>openworkflow-engine-http</artifactId></dependency>
    <dependency><groupId>com.forwardmeasure.openworkflow</groupId><artifactId>openworkflow-engine-event-http-server</artifactId></dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>openworkflow-micronaut-binding</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.forwardmeasure.jpa</groupId>
      <artifactId>forwardmeasure-jpa-micronaut</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-context</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-http</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut.jaxrs</groupId>
      <artifactId>micronaut-jaxrs-server</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut.jaxrs</groupId>
      <artifactId>micronaut-jaxrs-server-security</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut.sql</groupId>
      <artifactId>micronaut-hibernate-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut.security</groupId>
      <artifactId>micronaut-security-jwt</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.enterprise</groupId>
      <artifactId>jakarta.enterprise.cdi-api</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-inject-java</artifactId>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
