package com.forwardmeasure.openworkflow.workflow.runtime.api;

public enum ExecutionEventType {
  EXECUTION_STARTED,
  TASK_STARTED,
  TASK_SKIPPED,
  TASK_COMPLETED,
  EVENT_EMITTED,
  SUBSCRIPTION_CREATED,
  EVENT_RECEIVED,
  SUBSCRIPTION_COMPLETED,
  SUBSCRIPTION_CANCELLED,
  ASYNC_API_SUBSCRIPTION_CREATED,
  ASYNC_API_MESSAGE_RECEIVED,
  ASYNC_API_MESSAGE_FILTERED,
  ASYNC_API_SUBSCRIPTION_COMPLETED,
  ASYNC_API_SUBSCRIPTION_CANCELLED,
  CORRELATED_WORKER_STARTED,
  CORRELATED_WORKER_COMMAND_PUBLISHED,
  CORRELATED_WORKER_ACCEPTED,
  CORRELATED_WORKER_PROGRESS,
  CORRELATED_WORKER_COMPLETED,
  CORRELATED_WORKER_FAILED,
  CORRELATED_WORKER_CANCELLATION_REQUESTED,
  CORRELATED_WORKER_CANCELLED,
  CORRELATED_WORKER_OUTCOME_UNKNOWN,
  TIMER_SCHEDULED,
  TIMER_FIRED,
  TIMER_CANCELLED,
  ERROR_RAISED,
  ERROR_CAUGHT,
  RETRY_SCHEDULED,
  RETRY_STARTED,
  RETRY_EXHAUSTED,
  OPERATION_DISPATCHED,
  OPERATION_PROGRESS,
  OPERATION_RESULT_BUFFERED,
  OPERATION_FAILURE_BUFFERED,
  OPERATION_COMPLETED,
  OPERATION_CANCELLATION_REQUESTED,
  OPERATION_CANCELLED,
  OPERATION_OUTCOME_UNKNOWN,
  HUMAN_TASK_CREATED,
  HUMAN_TASK_OUTCOME_BUFFERED,
  HUMAN_TASK_APPROVED,
  HUMAN_TASK_REJECTED,
  HUMAN_TASK_REWORK_REQUESTED,
  HUMAN_TASK_EXPIRED,
  HUMAN_TASK_CANCELLATION_REQUESTED,
  HUMAN_TASK_CANCELLED,
  FORK_BRANCH_STARTED,
  FORK_BRANCH_COMPLETED,
  FORK_BRANCH_ABANDONED,
  ITERATION_STARTED,
  ITERATION_COMPLETED,
  EXECUTION_PAUSED,
  EXECUTION_RESUMED,
  EXECUTION_CANCEL_REQUESTED,
  EXECUTION_CANCELLED,
  EXECUTION_COMPLETED,
  EXECUTION_FAILED,
  EXECUTION_PURGE_REQUESTED,
  EXECUTION_PURGE_FAILED,
  EXECUTION_PURGED
}
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional information regarding
 * copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at https://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable
 * law or agreed to in writing, software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License
 * for the specific language governing permissions and limitations under the License.
 */
